/*global define */
define("go", ["locationHandler", "templatedUrlStrategy", "contentRetriever", "result"], function(locationHandler, urlStrategy, contentRetriever, result) {
  "use strict";

  var regex = /^go\s*\(\s*"([^"]+)"(?:\s*,\s*(.*))?\s*\)$/i;
  var queryRegex = /[a-z]+\(.*?\)(?=(?:\s*,\s*)|)/gi;
  var location = window.location;

  function setLocation(loc) {
    location = loc;
    contentRetriever.setLocation(loc);
  }

  function setWindow(win) {
    contentRetriever.setWindow(win);
  }

  // Get all values
  function getValues(jq, queries) {
    var i = 0, values = [], query;
    if(!queries) {
      return values;
    }
    for(; i < queries.length; i += 1) {
      query = queries[i];
      if(typeof query === "undefined") {
        continue;
      }
      values.push(contentRetriever.getContent(jq, query));
    }
    return values;
  }

  function getItemSafely (matches, position) {
    return matches && matches.length > position ? matches[position] : "";
  }

  // Perform the goToUrl operation (go). Force the current page to go do a different URL.
  function go (jq, url, queries) {
    var values = [];
    // get values from strategies
    if(queries && queries.length) {
      values = getValues(jq, queries);
    }
    return locationHandler.change(location, urlStrategy, url, values);
  }

  function handleGo (jq, statement) {
    var success = false, matches = regex.exec(statement), queries, url;
    if(!matches) {
      return result.NOT_HANDLED;
    }
    url = getItemSafely(matches, 1);
    queries = getItemSafely(matches, 2);
    if(queries) {
      queries = queries.match(queryRegex);
    }
    success = go(jq, url, queries);
    return success ? result.HANDLED : result.NOT_HANDLED;
  }

  function usage () {
    return 'Usage: go("templated-url", "query1", "query2",...,"queryN"); Go to a url that is generated by inserting the result of query 1..N.';
  }

  return {
    handle: handleGo,
    execute: go,
    toString: usage,
    setLocation: setLocation, /* Allow for replacing window.location for testing */
    setWindow: setWindow /* Allows for replacing window for testing */
  };
});
